apiVersion: v1
kind: Service
metadata:
  name: nats-lb
spec:
  type: LoadBalancer
  ports:
  - appProtocol: tcp
    name: nats
    port: 4222
    protocol: TCP
    targetPort: nats
  - appProtocol: tcp
    name: cluster
    port: 6222
    protocol: TCP
    targetPort: cluster
  selector:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: nats
    app.kubernetes.io/name: nats
