apiVersion: v1
kind: Pod
metadata:
  name: tutorial-cpu-memory
spec:
  containers:
    - name: tutorial-cpu-memory
      image: caddy
      workingDir: /etc
      resources:
        requests:
          cpu: 250m
          memory: 250Mi
        limits:
          cpu: 500m
          memory: 500Mi
      command: [ "caddy", "file-server", "--browse", "--listen", "0.0.0.0:8080" ]
  terminationGracePeriodSeconds: 1
