apiVersion: batch/v1
kind: Job
metadata:
  name: tutorial-job
spec:
  template:
    spec:
      containers:
      - name: tutorial-container
        image: caddy
        command: ["echo", "Hello, job!"]
      restartPolicy: Never
  backoffLimit: 2

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: tutorial-cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tutorial-container
            image: caddy
            command: ["/bin/sh", "-c", "date; echo Hello from the Kubernetes cluster"]
          restartPolicy: Never
      backoffLimit: 2
