apiVersion: v1
kind: Secret
metadata:
  name: tutorial-secret
data:
  username: ZWRvZ2F3YWNvbmFuCg==
  password: NDg2OQo=

---

apiVersion: v1
kind: Pod
metadata:
  name: tutorial-pod
  labels:
    app: tutorial-pod
spec:
  volumes:
  - name: tutorial-vol
    secret:
      secretName: tutorial-secret
  containers:
    - name: tutorial-container
      image: caddy
      volumeMounts:
      - name: tutorial-vol
        mountPath: /work
      env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: tutorial-secret
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: tutorial-secret
            key: password
      workingDir: /work
      command: [
        "caddy",
        "file-server",
        "--browse",
        "--listen",
        "0.0.0.0:8080",
      ]
  terminationGracePeriodSeconds: 1
